# verbos irregulares más comunes en inglés
VERBOS_IRREGULARES = {
    "be": "was",
    "become": "became",
    "begin": "began",
    "break": "broke",
    "bring": "brought",
    "build": "built",
    "buy": "bought",
    "catch": "caught",
    "choose": "chose",
    "come": "came",
    "cost": "cost",
    "cut": "cut",
    "do": "did",
    "draw": "drew",
    "drink": "drank",
    "drive": "drove",
    "eat": "ate",
    "fall": "fell",
    "feel": "felt",
    "find": "found",
    "fly": "flew",
    "forget": "forgot",
    "get": "got",
    "give": "gave",
    "go": "went",
    "grow": "grew",
    "have": "had",
    "hear": "heard",
    "hold": "held",
    "keep": "kept",
    "know": "knew",
    "leave": "left",
    "lose": "lost",
    "make": "made",
    "meet": "met",
    "pay": "paid",
    "put": "put",
    "read": "read",
    "ride": "rode",
    "ring": "rang",
    "run": "ran",
    "say": "said",
    "see": "saw",
    "sell": "sold",
    "send": "sent",
    "sit": "sat",
    "sleep": "slept",
    "speak": "spoke",
    "spend": "spent",
    "stand": "stood",
    "swim": "swam",
    "take": "took",
    "teach": "taught",
    "tell": "told",
    "think": "thought",
    "understand": "understood",
    "wear": "wore",
    "win": "won",
    "write": "wrote"
}

# diccionario inverso (pasado → base)
VERBOS_BASE = {v: k for k, v in VERBOS_IRREGULARES.items()}